* collection of tools that J finds useful

** Motivation

When conducting statistical analyses with the final outcome being a report/paper/document, there are three primary outputs: tables, figures and numbers.In practice, the generation of these outcomes is a highly iterative process, and each output is subject to change. Typical examples of such changes are changes in the input data, variable additions, changes in processing of the data or changes in estimation. The task of these helper functions is to provide glue to minimize the friction between writing analytical code and including its output in a document.

Experience of writing a report with a dozen figures figures and tables and around one hundred numbers.
Several times our input data changed, which required a an incredible annoying

biblatex/bibtex: similiar system exists for literature

main features:
- single point of truth for output: numbers, plot dimension, table layouts are
- inspection: functionality to see how an element will look in the final latex report
- avoid typos: no more manual copying of numbers from the terminal into the text


Several warnings are in order:
- These functions are highly idiosyncratically based on my experience, and in particular the software I use. Some components may have wider applicability, but others, in particular anything related to Emacs/ESS, are so tailored to my workflow that you may find them not helpful.
- While these functions facilitate updating of numbers, figures and tables, their substantive meaning may change. Validation of these numbers, via manual inspection or automated testing, always has to be kept in mind. 




tools included: 

** callgraph

- gl_clgr_objs: generate list of callgraph objects
  - edges
  - nodes
- gg_clgrph: generate a with 
- gw_fargs
- gl_funlinks
- gwd_clgrph: generate, write, display callgraph


** custom plotting framework

main activities are:
- generate -> gplt
- display -> dplt
- write -> wplt

rely on globally object l_plts: list of plots, where plots are stored by name (allows quick display/writing without regenerating plot)

some helper functions for common tasks:
- gdplt: generate plot and display in R
- dpltF: display plot written to pdf file (with zathura)
- dpltR: display plot in R 
- gwdplt: generate, write, display plot as pdf
- wdplt: write and display plot 


#+begin_src dot :file custom-plotting-framework.pdf

digraph D {
  node [shape = "box"]
  gp_X[label="gp_X: \ntakes in data, produces ggplot"]
  gc_plts[label="gc_plts:\n configuration for plots"]
  gplt[label="gplt:\ndo.call(gp_X)"]

  data -> gp_X
  other_params -> gp_X

  gc_plts -> data
  gc_plts -> other_params
  gc_plts -> gplt
  gp_X -> gplt
  gplt -> l_plts [label = "creates plot and assigns it to"]
  l_plts -> dplt [label = "reads from and displays"]
  l_plts -> wplt [label = "reads from and writes to file"]

}



#+end_src

#+RESULTS:
[[file:custom-plotting-framework.pdf]]

** custom table framwork
similar idea as plotting framework: 

- gt_X: takes in data, generates table list of
  - dt_fmd: data.table with cells
  - hline_after: positioning of hlines (some hlines are also provided by add_to_row)
  - add_to_row: rows added afterwards: list of pos and command of add_to_row strings
    used for column names (top), significance notes (bottom), variable group strings (inbetween)
  - align_cfg: latex-table columm specification, can include dcolumn types
  - number_cols: for wcpT, these the values in columns get wrapped in dollar sign to ensure math mode, which is somehow required for tables to work when exporting to word
  - optional: landscape, default = F. whether to flip the page  horizontal, to be used for wide tables
    
- gtbl: generates table-object list, places it in l_tbls
- wtbl: parses l_tbls object to xtable, then writes to tex file and cropped pdf file
  also 
- dtbl: displays cropped pdf file


things to do: make table framework more coherent

new functions:
- gc_signote
- gc_grpstrs
- fmt_cell
- fmt_pvlu

** word compability
More frequently than I would like to I have to produce word documents so that people can leave comments in them. Unfortunately, working with word in any kind of pipeline is fraught with difficulties, such as
- cross-references
- tables formatting gets messed up
- pdfs are not rendering

To deal with these issues, jtls includes a number of functionality to deal with word documents.

For preparation, tables and figures are generated also in word-compatible format; for figures this means as .pngs, for tables this means no D-columns, and columns with numbers are wrapped in dollar signs to ensure math mode. 

To generate a word document, an pre-export hook replaces the normal tables with word-compatible tables and the pdfs with pngs, then exports this file to `.tex`. `Pandoc` is then used to convert the `.tex` file to `.html`, which is then converted to `.docx`. I found that this process is able to produce a .docx with cross-references, figures and tables, which is mostly readable (imperfections are incorrect formatting of some in-text references, incorrect placement of the bibliography, and tables not looking great as column sizes, column alignments and consequently row heights are disregarded by word).




** overall things/functions that need to be defined

- gc_plts
- gc_tbls
- l_plts
- l_tbls



  



** custom number reference framework
- gc_refplt: generate the in-text references to plots (from a globally available `gc_plts` function)
- gc_ynkplt: generate the yank-plots (spaces where the actual plots appear)
- gc_reftbl: generate in-text references to tables
- wd_nbrs: write the data.table of number in the actual org-file to org-macros





